<?php

/**
 * BaseCompany
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $history
 * @property string $vision
 * @property string $mission
 * @property string $facebook
 * @property string $twitter
 * @property string $active
 * @property Doctrine_Collection $CompanyImages
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getName()          Returns the current record's "name" value
 * @method string              getDescription()   Returns the current record's "description" value
 * @method string              getHistory()       Returns the current record's "history" value
 * @method string              getVision()        Returns the current record's "vision" value
 * @method string              getMission()       Returns the current record's "mission" value
 * @method string              getFacebook()      Returns the current record's "facebook" value
 * @method string              getTwitter()       Returns the current record's "twitter" value
 * @method string              getActive()        Returns the current record's "active" value
 * @method Doctrine_Collection getCompanyImages() Returns the current record's "CompanyImages" collection
 * @method Company             setId()            Sets the current record's "id" value
 * @method Company             setName()          Sets the current record's "name" value
 * @method Company             setDescription()   Sets the current record's "description" value
 * @method Company             setHistory()       Sets the current record's "history" value
 * @method Company             setVision()        Sets the current record's "vision" value
 * @method Company             setMission()       Sets the current record's "mission" value
 * @method Company             setFacebook()      Sets the current record's "facebook" value
 * @method Company             setTwitter()       Sets the current record's "twitter" value
 * @method Company             setActive()        Sets the current record's "active" value
 * @method Company             setCompanyImages() Sets the current record's "CompanyImages" collection
 * 
 * @package    adehr
 * @subpackage model
 * @author     David Joan Tataje Mendoza <new.skin007@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompany extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_company');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             'notnull' => true,
             ));
        $this->hasColumn('history', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             'notnull' => true,
             ));
        $this->hasColumn('vision', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             'notnull' => true,
             ));
        $this->hasColumn('mission', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             'notnull' => true,
             ));
        $this->hasColumn('facebook', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             'notnull' => false,
             ));
        $this->hasColumn('twitter', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             'notnull' => false,
             ));
        $this->hasColumn('active', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             'fixed' => 1,
             'notnull' => true,
             'default' => 0,
             ));


        $this->index('i_active', array(
             'fields' => 
             array(
              0 => 'active',
             ),
             ));
        $this->index('i_name', array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => true,
             ));
        $this->option('boolean_columns', array(
             0 => 'active',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CompanyImage as CompanyImages', array(
             'local' => 'id',
             'foreign' => 'company_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggableext0 = new Doctrine_Template_SluggableExt(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggableext0);
    }
}