<?php

/**
 * BaseVideo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $embed
 * @property string $description
 * @property integer $rank
 * @property string $active
 * @property Doctrine_Collection $Posts
 * @property Doctrine_Collection $PostVideo
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getTitle()       Returns the current record's "title" value
 * @method string              getEmbed()       Returns the current record's "embed" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method integer             getRank()        Returns the current record's "rank" value
 * @method string              getActive()      Returns the current record's "active" value
 * @method Doctrine_Collection getPosts()       Returns the current record's "Posts" collection
 * @method Doctrine_Collection getPostVideo()   Returns the current record's "PostVideo" collection
 * @method Video               setId()          Sets the current record's "id" value
 * @method Video               setTitle()       Sets the current record's "title" value
 * @method Video               setEmbed()       Sets the current record's "embed" value
 * @method Video               setDescription() Sets the current record's "description" value
 * @method Video               setRank()        Sets the current record's "rank" value
 * @method Video               setActive()      Sets the current record's "active" value
 * @method Video               setPosts()       Sets the current record's "Posts" collection
 * @method Video               setPostVideo()   Sets the current record's "PostVideo" collection
 * 
 * @package    adehr
 * @subpackage model
 * @author     David Joan Tataje Mendoza <new.skin007@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVideo extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_video');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             'notnull' => true,
             ));
        $this->hasColumn('embed', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             'notnull' => false,
             ));
        $this->hasColumn('rank', 'integer', 5, array(
             'type' => 'integer',
             'length' => 5,
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('active', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             'fixed' => 1,
             'notnull' => true,
             'default' => 1,
             ));


        $this->index('u_title', array(
             'fields' => 
             array(
              0 => 'title',
             ),
             'type' => 'unique',
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => true,
             ));
        $this->option('boolean_columns', array(
             0 => 'active',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Post as Posts', array(
             'refClass' => 'PostVideo',
             'local' => 'video_id',
             'foreign' => 'post_id'));

        $this->hasMany('PostVideo', array(
             'local' => 'id',
             'foreign' => 'video_id'));

        $sluggableext0 = new Doctrine_Template_SluggableExt(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggableext0);
        $this->actAs($timestampable0);
    }
}