<?php

/**
 * BasePostVideo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $post_id
 * @property integer $video_id
 * @property Post $Post
 * @property Video $Video
 * 
 * @method integer   getPostId()   Returns the current record's "post_id" value
 * @method integer   getVideoId()  Returns the current record's "video_id" value
 * @method Post      getPost()     Returns the current record's "Post" value
 * @method Video     getVideo()    Returns the current record's "Video" value
 * @method PostVideo setPostId()   Sets the current record's "post_id" value
 * @method PostVideo setVideoId()  Sets the current record's "video_id" value
 * @method PostVideo setPost()     Sets the current record's "Post" value
 * @method PostVideo setVideo()    Sets the current record's "Video" value
 * 
 * @package    adehr
 * @subpackage model
 * @author     David Joan Tataje Mendoza <new.skin007@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePostVideo extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_post_video');
        $this->hasColumn('post_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             ));
        $this->hasColumn('video_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             ));

        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Post', array(
             'local' => 'post_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Video', array(
             'local' => 'video_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}