<?php

/**
 * BasePostMedia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $post_id
 * @property integer $media_id
 * @property Post $Post
 * @property Media $Media
 * 
 * @method integer   getPostId()   Returns the current record's "post_id" value
 * @method integer   getMediaId()  Returns the current record's "media_id" value
 * @method Post      getPost()     Returns the current record's "Post" value
 * @method Media     getMedia()    Returns the current record's "Media" value
 * @method PostMedia setPostId()   Sets the current record's "post_id" value
 * @method PostMedia setMediaId()  Sets the current record's "media_id" value
 * @method PostMedia setPost()     Sets the current record's "Post" value
 * @method PostMedia setMedia()    Sets the current record's "Media" value
 * 
 * @package    adehr
 * @subpackage model
 * @author     David Joan Tataje Mendoza <new.skin007@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePostMedia extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_post_media');
        $this->hasColumn('post_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             ));
        $this->hasColumn('media_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             ));

        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Post', array(
             'local' => 'post_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Media', array(
             'local' => 'media_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}