<?php

/**
 * BasePhoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $path
 * @property integer $size
 * @property string $full_mime
 * @property integer $rank
 * @property string $active
 * @property Doctrine_Collection $Posts
 * @property Doctrine_Collection $PostPhoto
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getTitle()     Returns the current record's "title" value
 * @method string              getPath()      Returns the current record's "path" value
 * @method integer             getSize()      Returns the current record's "size" value
 * @method string              getFullMime()  Returns the current record's "full_mime" value
 * @method integer             getRank()      Returns the current record's "rank" value
 * @method string              getActive()    Returns the current record's "active" value
 * @method Doctrine_Collection getPosts()     Returns the current record's "Posts" collection
 * @method Doctrine_Collection getPostPhoto() Returns the current record's "PostPhoto" collection
 * @method Photo               setId()        Sets the current record's "id" value
 * @method Photo               setTitle()     Sets the current record's "title" value
 * @method Photo               setPath()      Sets the current record's "path" value
 * @method Photo               setSize()      Sets the current record's "size" value
 * @method Photo               setFullMime()  Sets the current record's "full_mime" value
 * @method Photo               setRank()      Sets the current record's "rank" value
 * @method Photo               setActive()    Sets the current record's "active" value
 * @method Photo               setPosts()     Sets the current record's "Posts" collection
 * @method Photo               setPostPhoto() Sets the current record's "PostPhoto" collection
 * 
 * @package    adehr
 * @subpackage model
 * @author     David Joan Tataje Mendoza <new.skin007@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePhoto extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_photo');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             'notnull' => true,
             ));
        $this->hasColumn('path', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             'notnull' => true,
             ));
        $this->hasColumn('size', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('full_mime', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             'notnull' => true,
             ));
        $this->hasColumn('rank', 'integer', 5, array(
             'type' => 'integer',
             'length' => 5,
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('active', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             'fixed' => 1,
             'notnull' => true,
             'default' => 1,
             ));

        $this->option('symfony', array(
             'filter' => false,
             'form' => true,
             ));
        $this->option('boolean_columns', array(
             0 => 'active',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Post as Posts', array(
             'refClass' => 'PostPhoto',
             'local' => 'photo_id',
             'foreign' => 'post_id'));

        $this->hasMany('PostPhoto', array(
             'local' => 'id',
             'foreign' => 'photo_id'));

        $sluggableext0 = new Doctrine_Template_SluggableExt(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $thumbnailable0 = new Doctrine_Template_Thumbnailable();
        $this->actAs($sluggableext0);
        $this->actAs($timestampable0);
        $this->actAs($thumbnailable0);
    }
}