<?php

/**
 * BaseHomepage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $post_id
 * @property string $name
 * @property integer $rank
 * @property string $active
 * @property Post $Post
 * 
 * @method integer  getId()      Returns the current record's "id" value
 * @method integer  getPostId()  Returns the current record's "post_id" value
 * @method string   getName()    Returns the current record's "name" value
 * @method integer  getRank()    Returns the current record's "rank" value
 * @method string   getActive()  Returns the current record's "active" value
 * @method Post     getPost()    Returns the current record's "Post" value
 * @method Homepage setId()      Sets the current record's "id" value
 * @method Homepage setPostId()  Sets the current record's "post_id" value
 * @method Homepage setName()    Sets the current record's "name" value
 * @method Homepage setRank()    Sets the current record's "rank" value
 * @method Homepage setActive()  Sets the current record's "active" value
 * @method Homepage setPost()    Sets the current record's "Post" value
 * 
 * @package    adehr
 * @subpackage model
 * @author     David Joan Tataje Mendoza <new.skin007@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHomepage extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_homepage');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('post_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'notnull' => false,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             'notnull' => true,
             ));
        $this->hasColumn('rank', 'integer', 5, array(
             'type' => 'integer',
             'length' => 5,
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('active', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             'fixed' => 1,
             'notnull' => true,
             'default' => 0,
             ));


        $this->index('i_rank', array(
             'fields' => 
             array(
              0 => 'rank',
             ),
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => true,
             ));
        $this->option('boolean_columns', array(
             0 => 'active',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Post', array(
             'local' => 'post_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL',
             'onUpdate' => 'CASCADE'));

        $sluggableext0 = new Doctrine_Template_SluggableExt(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $thumbnailable0 = new Doctrine_Template_Thumbnailable();
        $this->actAs($sluggableext0);
        $this->actAs($timestampable0);
        $this->actAs($thumbnailable0);
    }
}