<?php

/**
 * BaseTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $active
 * @property Doctrine_Collection $Posts
 * @property Doctrine_Collection $PostTag
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method string              getName()    Returns the current record's "name" value
 * @method string              getActive()  Returns the current record's "active" value
 * @method Doctrine_Collection getPosts()   Returns the current record's "Posts" collection
 * @method Doctrine_Collection getPostTag() Returns the current record's "PostTag" collection
 * @method Tag                 setId()      Sets the current record's "id" value
 * @method Tag                 setName()    Sets the current record's "name" value
 * @method Tag                 setActive()  Sets the current record's "active" value
 * @method Tag                 setPosts()   Sets the current record's "Posts" collection
 * @method Tag                 setPostTag() Sets the current record's "PostTag" collection
 * 
 * @package    adehr
 * @subpackage model
 * @author     David Joan Tataje Mendoza <new.skin007@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTag extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_tag');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             'notnull' => true,
             ));
        $this->hasColumn('active', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             'fixed' => 1,
             'notnull' => true,
             'default' => 1,
             ));


        $this->index('u_name', array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'type' => 'unique',
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => true,
             ));
        $this->option('boolean_columns', array(
             0 => 'active',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Post as Posts', array(
             'refClass' => 'PostTag',
             'local' => 'tag_id',
             'foreign' => 'post_id'));

        $this->hasMany('PostTag', array(
             'local' => 'id',
             'foreign' => 'tag_id'));

        $sluggableext0 = new Doctrine_Template_SluggableExt(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggableext0);
        $this->actAs($timestampable0);
    }
}