<?php

/**
 * BasePicassa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $path
 * @property integer $rank
 * @property string $active
 * @property Post $Posts
 * 
 * @method integer getId()     Returns the current record's "id" value
 * @method string  getTitle()  Returns the current record's "title" value
 * @method string  getPath()   Returns the current record's "path" value
 * @method integer getRank()   Returns the current record's "rank" value
 * @method string  getActive() Returns the current record's "active" value
 * @method Post    getPosts()  Returns the current record's "Posts" value
 * @method Picassa setId()     Sets the current record's "id" value
 * @method Picassa setTitle()  Sets the current record's "title" value
 * @method Picassa setPath()   Sets the current record's "path" value
 * @method Picassa setRank()   Sets the current record's "rank" value
 * @method Picassa setActive() Sets the current record's "active" value
 * @method Picassa setPosts()  Sets the current record's "Posts" value
 * 
 * @package    adehr
 * @subpackage model
 * @author     David Joan Tataje Mendoza <new.skin007@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePicassa extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_picassa');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             'notnull' => true,
             ));
        $this->hasColumn('path', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             'notnull' => true,
             ));
        $this->hasColumn('rank', 'integer', 5, array(
             'type' => 'integer',
             'length' => 5,
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('active', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             'fixed' => 1,
             'notnull' => true,
             'default' => 1,
             ));


        $this->index('u_title', array(
             'fields' => 
             array(
              0 => 'title',
             ),
             'type' => 'unique',
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => true,
             ));
        $this->option('boolean_columns', array(
             0 => 'active',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Post as Posts', array(
             'local' => 'id',
             'foreign' => 'picassa_id'));

        $sluggableext0 = new Doctrine_Template_SluggableExt(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggableext0);
        $this->actAs($timestampable0);
    }
}