<?php

/**
 * Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    adehr
 * @subpackage model
 * @author     David Joan Tataje Mendoza <new.skin007@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Category extends BaseCategory
{

    public function save(Doctrine_Connection $conn = null) {
        if ($this->isNew()) {
            $this->setNewRank();
        }
        parent::save($conn);
    }
    
    public function setNewRank() {
        $rank = $this->getTable()->getNewRank();
        $this->setRank($rank);
    }
    
    public function getLastPost()
    {
        return $this->getPosts()->getLast();
    }
    
    public function getPostName()
    {
        $result = "<ul>";
        foreach ($this->getPosts() as $post) {
            $result = $result . "<li>".$post->getTitle() . '</li>';
        }
        return $result."</ul>";        
    }
}