<?php

/**
 * CompanyImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompanyImageTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompanyImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CompanyImage');
    }
    
const
    STATUS_ACTIVE       = 1,
    STATUS_INACTIVE     = 0;
    
  protected static
    $status                = array
                             (
                               self::STATUS_ACTIVE     => 'Si'  ,
                               self::STATUS_INACTIVE   => 'No',
                             );

  public function getStatuss()
  {
    return self::$status;
  }
  
    public function getPathDir()
  {
    return sfConfig::get('app_company_image_images_dir');
  }
  
  public function getImagePath()
  {
    return sfConfig::get('app_company_image_images_path');
  }    
}    