<?php

/**
 * HomepageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HomepageTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object HomepageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Homepage');
    }
    
    public function getHomepage()
    {
            $q = $this->createAliasQuery()
         ->leftJoin('h.Post p')
         ->where('p.status = ?', PostTable::STATUS_PUBLISHED)
         ->orderBy('h.rank ASC')
         ->limit(10);
         
    return $q->execute();
    }
}