<?php

/**
 * MenuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MenuTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MenuTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Menu');
    }
}