<?php

/**
 * PhotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhotoTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PhotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Photo');
    }
    
  public function getPathDir()
  {
    return sfConfig::get('app_photo_dir');
  }
  
  public function getPathPath()
  {
    return sfConfig::get('app_photo_path');
  }    
  
  
    public function getNewRank()
  {
  	 $q = $this->createQuery('a')
  	           ->addSelect('MAX(rank)');
  	           
  	 $dato = $q->execute()->getFirst()->toArray();
  	 return $dato['MAX']+1;
  	 
  } 
}