<?php

/**
 * PhotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhotoTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PhotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Photo');
    }
    
  public function getPathDir()
  {
    return sfConfig::get('app_photo_dir');
  }
  
  public function getPathPath()
  {
    return sfConfig::get('app_photo_path');
  }    
  
  
  public function getNewRank()
  {
  	 $q = $this->createQuery('a')
  	           ->addSelect('MAX(rank)');
  	           
  	 $dato = $q->execute()->getFirst()->toArray();
  	 return $dato['MAX']+1;	 
  } 
  
  public function findByTitleLike($name, $limit = 20)
  {
    $q = $this->createAliasQuery('p')
         ->where('LOWER(p.title) LIKE ?', '%'.Stringkit::strtolower($name).'%')
         ->limit($limit);
    
    return $q->execute();
  }
  
  public function getPhotoGallery()
  {
    $q = $this->createAliasQuery()
         ->where('p.active = 1')
         ->orderBy('p.rank ASC')
         ->limit(20);
         
    return $q->execute();
  }  
}