<?php

/**
 * PicassaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PicassaTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PicassaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Picassa');
    }
}