<?php

/**
 * PostMediaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostMediaTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostMediaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PostMedia');
    }
}