<?php

/**
 * PostTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostTagTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostTagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PostTag');
    }
}