<?php

/**
 * PostVideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostVideoTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostVideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PostVideo');
    }
}