<?php

/**
 * PostPhotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostPhotoTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostPhotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PostPhoto');
    }
}