<?php

/**
 * VideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VideoTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object VideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Video');
    }
    
    public function getNewRank()
  {
  	 $q = $this->createQuery('a')
  	           ->addSelect('MAX(rank)');
  	           
  	 $dato = $q->execute()->getFirst()->toArray();
  	 return $dato['MAX']+1;
  	 
  }     
  
  public function findByTitleLike($name, $limit = 20)
  {
    $q = $this->createAliasQuery('v')
         ->where('LOWER(v.title) LIKE ?', '%'.Stringkit::strtolower($name).'%')
         ->limit($limit);
    
    return $q->execute();
  }  
  
  public function getVideoGallery()
  {
    $q = $this->createAliasQuery()
         ->where('v.active = 1')
         ->orderBy('v.rank ASC')
         ->limit(20);
         
    return $q->execute();
  }    
}