#Sitemap
sitemap:
  url:             /sitemap
  param:           { module: Home, action: sitemap }

#Feed
feed_last_posts:
  url:             /feed
  param:           { module: Feed, action: lastPosts }

feed_category_last_posts:
  url:             /categoria/:category_slug/feed
  param:           { module: Feed, action: lastPosts }

#Contactenos
image:
  url:             /imagen
  param:           { module: Home, action: image }

contact:
  url:             /contactenos
  param:           { module: Home, action: contact }

post_tag:
  url:             /tag/:slug
  param:           { module: Home, action: tag }
  requirements:    { slug: \w+ }

post_section:
  url:             /seccion/:slug
  param:           { module: Home, action: section }
  requirements:    { slug: \w+ }

post_show:
  url:             /articulo/:slug
  param:           { module: Home, action: show }
  requirements:    { slug: \w+ }

# default rules
homepage:
  url:   /
  param: { module: Home, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
