default:
  http_metas:
    content-type: text/html
  metas:
    title:         Bienvenidos a ADEHR
    description:   '"ADEHR. Asociación para el Desarrollo Humano Runamasinchiqpaq. Organismo sin fines de lucro de Perú dedicado a la promoción y defensa de los derechos humanos."'
    keywords:      adehr, peru, asociacion, desarrollo, humano, runamasinchiqpaq, violencia, derechos, humanos,victimas, familiares, deudos, jaime, ayala, sulca, masacre, accomarca, pucayacu, matero, casos,asesoria, legal, memoria, ddhh, matanza, desaparicion, tortura
    language:      es
    robots:        index, follow
   
  stylesheets:
    - frontend/menu.css: { position: first }    
    - frontend/style.css: { media: screen }        
    - fancybox/jquery.fancybox.css: { position: first }
    - general/jquery-ui-1.8.custom.css: { media: screen }

  javascripts:
    - jquery/jquery-ui-1.8.min.js
    - frontend/menu.js
    - frontend/javascript.js
    - frontend/jquery.cross-slide.min.js
    - frontend/jquery.jcarousel.min.js
    - fancybox/jquery.fancybox.pack.js
    

  has_layout:     true
  layout:         layout