all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=localhost;dbname=adehr
      username: root
      password: 'root'
      #dsn:      mysql:host=localhost;dbname=adehrper_site
      #username: adehrper_root
      #password: 'dz5Zeal_5L]3'