Picassa:
  tableName:                           t_picassa
  actAs:
    SluggableExt:                      { fields: [ title ] }
    Timestampable:
  columns:
    id:                                { type: integer  , length: 20 , primary: true    , autoincrement: true         }
    title:                             { type: string   , length: 100                   , notnull: true               }
    path:                              { type: string   , length: 255                   , notnull: true               }
    rank:                              { type: integer  , length: 5                     , notnull: true , default: 0  }
    active:                            { type: string   , length: 1  , fixed: true      , notnull: true , default: 1  }
  indexes:
    u_title:                           { fields: [ title ]                               , type: unique               }
  relations:
    Post:                              { class: Post , local: id  , foreign: picassa_id , type: one , alias: Posts    }
  options:
    symfony:                           { filter: false, form: true }
    boolean_columns:                   [ active ]