Video:
  tableName:                           t_video
  actAs:
    SluggableExt:                      { fields: [ title ] }
    Timestampable:
  columns:
    id:                                { type: integer  , length: 20 , primary: true    , autoincrement: true                                                  }
    title:                             { type: string   , length: 100                   , notnull: true                                                        }
    embed:                             { type: string   , length: 10000                   , notnull: true                                                      }
    description:                       { type: string   , length: 10000                  , notnull: false                                                      }
    rank:                              { type: integer  , length: 5                     , notnull: true , default: 0                                           }
    active:                            { type: string   , length: 1  , fixed: true      , notnull: true , default: 1                                           }
  indexes:
    #u_title:                           { fields: [ title ]                               , type: unique                                                         }
  relations:
    Post:                              { class: Post             , local: video_id   , foreign: post_id  , alias: Posts, refClass: PostVideo             }
  options:
    symfony:                           { filter: false, form: true }
    boolean_columns:                   [ active ]        

PostVideo:
  tableName:                           t_post_video
  actAs:
    Timestampable:                     { updated: { disabled: true } }
  columns:
    post_id:                           { type: integer  , length: 20 , primary: true                                                                           }
    video_id:                          { type: integer  , length: 20 , primary: true                                                                           }
  relations:
    Post:                              { class: Post          , local: post_id    , foreign: id, type: one , alias: Post  , onDelete: CASCADE , onUpdate: CASCADE }
    Video:                             { class: Video         , local: video_id   , foreign: id, type: one , alias: Video , onDelete: CASCADE , onUpdate: CASCADE }
  options:
    symfony:                           { filter: false, form: false }